import { useEffect, useState } from "react";
import type { AuthResponse, QuizInput, QuizOption, QuizQuestionInput, TeacherQuiz } from "@quizarena/shared-types";

const apiUrl = import.meta.env.VITE_API_URL ?? "http://localhost:3001";
const newQuestion = (): QuizQuestionInput => ({ text: "", options: [{ text: "", isCorrect: true }, { text: "", isCorrect: false }], timeLimitSec: 20, points: 1000 });
const newQuiz = (): QuizInput => ({ title: "", description: "", isPublic: false, questions: [newQuestion()] });
type ApiError = { error?: string };
const getError = (value: unknown) => typeof value === "object" && value !== null && "error" in value && typeof (value as ApiError).error === "string" ? (value as ApiError).error : "Request failed.";

async function api<T>(path: string, options: RequestInit = {}, token?: string): Promise<T> {
  const response = await fetch(`${apiUrl}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  if (response.status === 204) return undefined as T;
  const body: unknown = await response.json();
  if (!response.ok) throw new Error(getError(body));
  return body as T;
}

function Auth({ done }: { done: (value: AuthResponse) => void }) {
  const [signup, setSignup] = useState(true); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(""); try { done(await api<AuthResponse>(`/api/auth/${signup ? "signup" : "login"}`, { method: "POST", body: JSON.stringify(signup ? { name, email, password } : { email, password }) })); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not continue."); } }
  return <main className="teacher-auth"><section><p className="eyebrow">QUIZ KHELO FOR TEACHERS</p><h1>Make every answer count.</h1><p>Build live quizzes your classroom will want to play.</p></section><form className="teacher-panel" onSubmit={submit}><h2>{signup ? "Create account" : "Welcome back"}</h2>{signup && <label>Name<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} required /></label>}<label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={8} required /></label>{message && <p className="form-error">{message}</p>}<button className="teacher-primary">{signup ? "Create account" : "Log in"}</button><button className="teacher-link" type="button" onClick={() => setSignup(!signup)}>{signup ? "Already have an account? Log in" : "Need an account? Sign up"}</button></form></main>;
}

function Builder({ value, change }: { value: QuizInput; change: (next: QuizInput) => void }) {
  const updateQuestion = (index: number, next: Partial<QuizQuestionInput>) => change({ ...value, questions: value.questions.map((question, i) => i === index ? { ...question, ...next } : question) });
  const updateOption = (questionIndex: number, optionIndex: number, next: Partial<QuizOption>) => updateQuestion(questionIndex, { options: value.questions[questionIndex].options.map((option, i) => i === optionIndex ? { ...option, ...next } : option) });
  function reorder(index: number, by: -1 | 1) { const target = index + by; if (target < 0 || target >= value.questions.length) return; const questions = [...value.questions]; [questions[index], questions[target]] = [questions[target], questions[index]]; change({ ...value, questions }); }
  return <div className="builder"><section className="teacher-panel quiz-meta"><label>Quiz title<input value={value.title} onChange={(event) => change({ ...value, title: event.target.value })} placeholder="e.g. World capitals" /></label><label>Description <small>(optional)</small><textarea value={value.description ?? ""} onChange={(event) => change({ ...value, description: event.target.value })} /></label><label className="teacher-check"><input type="checkbox" checked={value.isPublic} onChange={(event) => change({ ...value, isPublic: event.target.checked })} />Make this quiz public</label></section>{value.questions.map((question, questionIndex) => <article className="teacher-panel question" key={questionIndex}><div className="question-header"><strong>Question {questionIndex + 1}</strong><span><button type="button" onClick={() => reorder(questionIndex, -1)} disabled={questionIndex === 0}>↑</button><button type="button" onClick={() => reorder(questionIndex, 1)} disabled={questionIndex === value.questions.length - 1}>↓</button><button type="button" onClick={() => change({ ...value, questions: value.questions.filter((_, i) => i !== questionIndex) })} disabled={value.questions.length === 1}>Remove</button></span></div><label>Question<input value={question.text} onChange={(event) => updateQuestion(questionIndex, { text: event.target.value })} placeholder="Write your question" /></label><div className="question-numbers"><label>Time (seconds)<input type="number" min="5" max="300" value={question.timeLimitSec} onChange={(event) => updateQuestion(questionIndex, { timeLimitSec: Number(event.target.value) })} /></label><label>Points<input type="number" min="0" max="10000" value={question.points} onChange={(event) => updateQuestion(questionIndex, { points: Number(event.target.value) })} /></label></div><fieldset><legend>Answer options (choose the correct one)</legend>{question.options.map((option, optionIndex) => <div className="answer" key={optionIndex}><input type="radio" name={`correct-${questionIndex}`} checked={option.isCorrect} onChange={() => updateQuestion(questionIndex, { options: question.options.map((item, i) => ({ ...item, isCorrect: i === optionIndex })) })} /><input value={option.text} onChange={(event) => updateOption(questionIndex, optionIndex, { text: event.target.value })} placeholder={`Option ${optionIndex + 1}`} /><button type="button" disabled={question.options.length === 2} onClick={() => updateQuestion(questionIndex, { options: question.options.filter((_, i) => i !== optionIndex) })}>×</button></div>)}{question.options.length < 4 && <button className="teacher-link" type="button" onClick={() => updateQuestion(questionIndex, { options: [...question.options, { text: "", isCorrect: false }] })}>+ Add option</button>}</fieldset></article>)}<button className="teacher-add" type="button" onClick={() => change({ ...value, questions: [...value.questions, newQuestion()] })}>+ Add question</button></div>;
}

export function DashboardApp() {
  const [auth, setAuth] = useState<AuthResponse | null>(() => { const stored = localStorage.getItem("quizarena-teacher"); return stored ? JSON.parse(stored) as AuthResponse : null; });
  const [quizzes, setQuizzes] = useState<TeacherQuiz[]>([]); const [id, setId] = useState<string | null>(null); const [draft, setDraft] = useState<QuizInput>(newQuiz); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!auth) return; api<TeacherQuiz[]>("/api/quizzes", {}, auth.token).then(setQuizzes).catch((reason: unknown) => setNotice(reason instanceof Error ? reason.message : "Could not load quizzes.")); }, [auth]);
  function select(quiz: TeacherQuiz) { setId(quiz.id); setDraft({ title: quiz.title, description: quiz.description, isPublic: quiz.isPublic, questions: quiz.questions }); }
  async function save() { if (!auth) return; setSaving(true); setNotice(""); try { const saved = await api<TeacherQuiz>(id ? `/api/quizzes/${id}` : "/api/quizzes", { method: id ? "PUT" : "POST", body: JSON.stringify(draft) }, auth.token); setQuizzes((current) => id ? current.map((quiz) => quiz.id === saved.id ? saved : quiz) : [saved, ...current]); setId(saved.id); setNotice("Quiz saved."); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Could not save quiz."); } finally { setSaving(false); } }
  async function remove() { if (!auth || !id || !window.confirm("Delete this quiz?")) return; setSaving(true); try { await api<void>(`/api/quizzes/${id}`, { method: "DELETE" }, auth.token); setQuizzes((current) => current.filter((quiz) => quiz.id !== id)); setId(null); setDraft(newQuiz()); setNotice("Quiz deleted."); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Could not delete quiz."); } finally { setSaving(false); } }
  if (!auth) return <Auth done={(next) => { localStorage.setItem("quizarena-teacher", JSON.stringify(next)); setAuth(next); }} />;
  return <main className="teacher-dashboard"><header><div><p className="eyebrow">QUIZ KHELO</p><h1>Your quizzes</h1></div><div>{auth.teacher.name} <button className="teacher-link" onClick={() => { localStorage.removeItem("quizarena-teacher"); setAuth(null); }}>Log out</button></div></header><div className="teacher-layout"><aside><button className="teacher-primary" onClick={() => { setId(null); setDraft(newQuiz()); }}>+ New quiz</button>{quizzes.map((quiz) => <button className={quiz.id === id ? "quiz-tab active" : "quiz-tab"} key={quiz.id} onClick={() => select(quiz)}>{quiz.title}<small>{quiz.questions.length} questions</small></button>)}</aside><section><div className="builder-top"><h2>{draft.title || "New quiz"}</h2><div><button className="teacher-primary" onClick={save} disabled={saving}>{saving ? "Saving…" : "Save quiz"}</button>{id && <button className="teacher-delete" onClick={remove} disabled={saving}>Delete</button>}</div></div>{notice && <p className="teacher-notice">{notice}</p>}<Builder value={draft} change={setDraft} /></section></div></main>;
}
